FROM python:3.8

WORKDIR /opt/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install confluent_kafka
RUN pip install kafka-python
COPY . .

CMD ["python3", "./producer.py"]
