FROM python:3.10

WORKDIR /opt/app

COPY requirements.txt ./

RUN pip install -r requirements.txt
#RUN pip install confluent_kafka
#RUN pip install kafka-python
COPY . .

CMD ["python3", "producer.py"]
