# Use root/example as user/password credentials
version: '3.8'

services:
  app:
    build: .
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: encuestas
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongosecret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_BROKER: kafka-broker-1:9092
    ports:
      - "5002:5000"
    depends_on:
      - zookeeper
      - mongodb
      - kafka-broker-1
    volumes:
      - .:/opt/app
    command: poetry run python3 -m flask run --host=0.0.0.0 --port=5000
    networks:
      - web

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongosecret
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - web

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongosecret
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    networks:
      - web

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - web

  kafka-broker-1:
    image: apache/kafka:latest
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker-1:29092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - web

networks:
  web:

volumes:
  mongodb-data:
